spring:
  application:
    name: Blog
  # 配置数据源
  datasource:
    name: blog-datasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_blog_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 88888888
    type: com.zaxxer.hikari.HikariDataSource

    # 配置连接池信息
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 120000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML
  
  mvc:
    static-path-pattern: /**
    
  servlet:
    # 文件上传大小限制
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: classpath:/static/
  # 日志输出着色
  output:
    ansi:
      enabled: detect

# 整合 mybatis 配置
mybatis:
  # 配置 xml 文件位置
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 开启驼峰命名法
    map-underscore-to-camel-case: true

server:
  # 端口
  port: 28083

# 日志级别
logging:
  group:
    group1:
#      - cn.lulucar.blog.controller
#      - cn.lulucar.blog.service
      - cn.lulucar.blog.mapper
  level:
    group1: debug
  
# 定义文件上传目录  
file: 
  upload: 
    dir: E:/upload/